---
title: "Tidymodels"
author: "Shrish Tariq"
format: html
execute: 
  echo: false
---

```{r}
#| message: false

library(tidymodels)
library(tidyverse)
library(broom)
library(ordered)

titanic <- read_csv("data/titanic.csv")

titanic <- titanic %>%
  mutate(
    class_sex = paste(Pclass, Sex, sep = "-")
  )
```

```{r}
titanic <- read_csv("data/titanic.csv", show_col_types = FALSE) |>
  mutate(class_sex = paste(Pclass, Sex, sep = "-"))
titanic
```

```{r}
linear_reg() |> set_engine("lm")
```

```{r}
mod_linear <- linear_reg() |> set_engine("lm") |> fit (Age ~ Pclass + Sex, data = titanic)
mod_linear
```

```{r}
tidy(mod_linear)
```

```{r}
#| results: asis


build_equation <- function(coefs, outcome) {
  has_intercept <- "(Intercept)" %in% coefs$term
  other <- coefs[coefs$term != "(Intercept)", ]
  parts <- purrr::map2_chr(other$term, round(other$estimate, 2), function(term, est) {
    sign <- if (est >= 0) "+" else "-"
    paste0(sign, " ", abs(est), " \\times \\text{", term, "}")
  })
  lead <- if (has_intercept) as.character(round(coefs$estimate[coefs$term == "(Intercept)"], 2)) else NULL
  rhs <- paste(c(lead, parts), collapse = " ")
  paste0("$$\\text{", outcome, "} = ", rhs, "$$")
}
mod_linear_glm <- linear_reg() |>
  set_engine("glm") |>
  fit(Age ~ Pclass + Sex, data = titanic)

cat(build_equation(tidy(mod_linear), "Age"))
cat(build_equation(tidy(mod_linear_glm), "Age (glm)"))
```

```{r}
#| results: asis
mod_logistic <- logistic_reg() |>
  set_engine("glm") |>
  fit(factor(Survived, levels = c(0, 1)) ~ Age + Pclass + Sex, data = titanic)

cat(build_equation(tidy(mod_logistic), "logit(P(Survived))"))
```

```{r}
#| cache: true
mod_logistic <- logistic_reg() |>
  set_engine("glm") |>
  fit(factor(Survived, levels = c(0, 1)) ~ Age + Pclass + Sex, data = titanic)
mod_logistic
```
Multinomial Regression 

```{r}
count(titanic, class_sex, sort = TRUE)
```

```{r}
#| results: asis
mod_multinomial <- multinom_reg() |>
  set_engine("nnet") |>
  fit(factor(class_sex) ~ Age + Survived, data = titanic)

mod_multinomial
mod_multinomial_coefs <- tidy(mod_multinomial) |> filter(y.level == "3rd-male")
cat(build_equation(mod_multinomial_coefs, "log-odds(3rd-male vs. 1st-female)"))
```


